community:
  name: Community
  timezone: America/Los_Angeles
  channels:
    - Police North
    - Police South
    - County North
    - Highway Patrol
    - County Fire
  tones:
    Station 1:
      file: station1.wav
    Emergency Traffic:
      file: emergency.wav
      marker: emergency_marker.wav
    Volunteer Fire:
      file: volunteer_fire.wav
    Volunteer EMS:
      file: volunteer_ems.wav
port: 8081
