community:
  name: Community
  timezone: America/Los_Angeles
  channels:
    - Police North
    - Police South
    - County North
    - Highway Patrol
tones:
  Station 1:
    file: station1.wav
  Emergency Traffic:
    file: emergency.wav
    marker: emergency_marker.wav
port: 8080
